Sach01/Sach01/Models/Sach.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sach01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        { 
            HinhAnh = "~/images/add.png";
            this.ChiTietMuaHangs = new HashSet<ChiTietMuaHang>();
        }
        

        public int IdSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<decimal> UnitGia { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string Available { get; set; }
        public Nullable<int> IdDanhMuc { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> IdTacGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMuaHang> ChiTietMuaHangs { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual TacGia TacGia { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}

Sach01/Sach01/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sach01.Models;
using System.Data;
using System.IO;
using System.Data.Entity;

namespace Sach01.Controllers
{
    public class SachController : Controller
    {
        Sach01Entities _db = new Sach01Entities();
        // GET: Sach
        public ActionResult Index(string searchBy,string search)
        {
            if (searchBy == "TenSach")
                return View(_db.Saches.Where(s=>s.TenSach.StartsWith(search)).ToList());
            else if(searchBy == "Available")
                return View(_db.Saches.Where(s => s.Available==search).ToList());
            else // None
            return View(_db.Saches.ToList());
        }

        // GET: Sach/Details/5
        public ActionResult Details(int id)
        {
            return View(_db.Saches.Where(s => s.IdSach == id).FirstOrDefault());
        }

        // GET: Sach/Create
        public ActionResult Create()
        {
            Sach sach = new Sach();
            return View(sach);
        }

        // POST: Sach/Create
        [HttpPost]
        public ActionResult Create(Sach sach)
        {
            try
            {
                // TODO: Add insert logic here
                if (sach.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(sach.ImageUpload.FileName);
                    string extension = Path.GetExtension(sach.ImageUpload.FileName);
                    fileName = fileName + extension;
                    sach.HinhAnh = "~/images/" + fileName;
                    sach.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/images/"), fileName));
                }
                _db.Saches.Add(sach);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sach/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_db.Saches.Where(s => s.IdSach == id).FirstOrDefault());
        }

        // POST: Sach/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Sach sach)
        {
            try
            {
                // TODO: Add update logic here
                if (sach.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(sach.ImageUpload.FileName);
                    string extension = Path.GetExtension(sach.ImageUpload.FileName);
                    fileName = fileName + extension;
                    sach.HinhAnh = "~/images/" + fileName;
                    sach.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/images/"), fileName));
                }
                _db.Entry(sach).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sach/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_db.Saches.Where(s => s.IdSach == id).FirstOrDefault());
        }

        // POST: Sach/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Sach sach)
        {
            try
            {
                // TODO: Add delete logic here
                sach = _db.Saches.Where(s => s.IdSach == id).FirstOrDefault();
                _db.Saches.Remove(sach);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ChonDanhMuc()
        {
            DanhMuc dm = new DanhMuc();
            dm.DSDanhMuc = _db.DanhMucs.ToList<DanhMuc>();
            return PartialView(dm);
        }
    }
}

Sach01/Sach01/Views/Sach/ChonDanhMuc.cshtml
@model Sach01.Models.DanhMuc
@Html.DropDownListFor(model => model.IdDanhMuc, new SelectList(Model.DSDanhMuc,
    "IdDanhMuc", "TenDanhMuc", "--Select--"))

Sach01/Sach01/Views/Sach/Create.cshtml
@model Sach01.Models.Sach

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <style>
        select{
            width:400px;
            height:34px;
            border-radius:5px;
        }
    </style>
</head>

<h2>Create</h2>


@using (Html.BeginForm("Create","Sach", FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sach</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdSach)

        <div class="form-group">
            @Html.LabelFor(model => model.TenSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })
                <img src="@Url.Content(Model.HinhAnh)" style="height:100px; width:100px; margin:10px;" id="previewImage" />
                <input type="file" name="ImageUpload" onchange="ShowImagePreview(this, document.getElementById('previewImage'))" />
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayTao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayTao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayTao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Available, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.IdDanhMuc, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-2">
                <h5 style="font-weight:bold">Danh muc</h5>
            </div>
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.IdDanhMuc, new { htmlAttributes = new { @class = "form-control" } })*@
                <div style="width:300px; height:auto">
                    @{ Html.RenderAction("ChonDanhMuc", "Sach");}
                </div>
                @Html.ValidationMessageFor(model => model.IdDanhMuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTacGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdTacGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdTacGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sach01/Sach01/Views/Sach/Delete.cshtml
@model Sach01.Models.Sach

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayTao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Available)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdDanhMuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdDanhMuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdTacGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdTacGia)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Sach01/Sach01/Views/Sach/Details.cshtml
@model Sach01.Models.Sach

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Sach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            <img src="@Url.Content(Model.HinhAnh)" style="height:200px;width:200px; margin:10px;"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayTao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Available)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdDanhMuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdDanhMuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdTacGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdTacGia)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Sach01/Sach01/Views/Sach/Edit.cshtml
@model Sach01.Models.Sach

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit","Sach", FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sach</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdSach)
        @Html.HiddenFor(model => model.HinhAnh)

        <div class="form-group">
            @Html.LabelFor(model => model.TenSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })*@
                <img src="@Url.Content(Model.HinhAnh)" style="height:100px; width:100px; margin:10px;" id="previewImage" />
                <input type="file" name="ImageUpload" onchange="ShowImagePreview(this, document.getElementById('previewImage'))"/>
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayTao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayTao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayTao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Available, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdDanhMuc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdDanhMuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdDanhMuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTacGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdTacGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdTacGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sach01/Sach01/Views/Sach/Index.cshtml
@model IEnumerable<Sach01.Models.Sach>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div style="text-align:center">
    @using (Html.BeginForm("Index", "Sach"))
    {
        <b>Search by: </b>@Html.RadioButton("searchBy", "TenSach")<text>Tên Sách</text>
        @Html.RadioButton("searchBy", "Available")<text>Available</text>
        @Html.RadioButton("searchBy", "None", true)<text>None</text><br />
        @Html.TextBox("search") <input type="submit" value="Search" />
    }
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitGia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgayTao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Available)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdDanhMuc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MoTa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoLuong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdTacGia)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitGia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HinhAnh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayTao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Available)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdDanhMuc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MoTa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoLuong)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdTacGia)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdSach }) |
            @Html.ActionLink("Details", "Details", new { id = item.IdSach }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.IdSach })
        </td>
    </tr>
}

</table>